### PR TITLE
Permissions Screen

### PR DESCRIPTION
**Pull request by astyfre**
UI implemented. Switches also request permissions for the app to use features.

### CODE REVIEW

**Comment by astyfre** [comment]
Both permissions and Notifications screens are working. Permissions screen has functionality

**Comment by astyfre** [comment]
Access screen added - will look into throwing data to firebase for who and what data users want to give access to

**Review by deegle0-0 — CHANGES_REQUESTED** [review]
Hey! So there is a bug that shows up straight away, 

When I turn the permission on after turning it on and off once it shows the error 
image

Extra note: 
A little unclear about the Access page, when I type should it search in the contacts as I type?

**Review by deegle0-0 — APPROVED** [review]
Good work Aston!

**Pull request merged**
